apiVersion: apps/v1
kind: Deployment
metadata:
  name: snpe-quantizer
  namespace: snpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snpe-quantizer
  template:
    metadata:
      labels:
        app: snpe-quantizer
    spec:
      containers:
      - name: snpe-quantizer
        image: snpecontainerregistry001.azurecr.io/quantizer:1.23
        resources:
          limits:
            cpu: 4

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: snpe-quantizer
  namespace: snpe
spec:
  maxReplicas: 100 # define max replica count
  minReplicas: 1   # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snpe-quantizer
  targetCPUUtilizationPercentage: 40 # target CPU utilization