adaptive: true
attn_type: 0
clamp_len: -1
cutoffs:
- 59997
- 99997
- 639997
- 50264
d_embed: -1
d_head: -1
d_inner:
- 1543
- 1398
- 660
- 767
- 936
- 792
- 842
- 1388
- 1592
- 820
- 954
- 1361
- 877
- 1081
- 946
d_model: 256
div_val: 2
dropatt: 0.0
dropout: 0.1
dtype: null
ext_len: 0
mem_len: 192
n_head:
- 2
- 2
- 2
- 2
- 4
- 2
- 4
- 4
- 2
- 4
- 8
- 8
- 2
- 4
- 2
n_layer: 15
n_token: 50264
pre_lnorm: false
primer_conv: false
primer_square: false
proj_init_std: 0.01
same_length: false
sample_softmax: -1
tgt_len: 32
tie_projs:
- false
- false
- false
- false
tie_weight: true
use_cache: false
weight_init_range: 0.1
weight_init_std: 0.02
weight_init_type: normal
